import json
from pathlib import Path


def write_isolated_runtime_receipt(
    path: Path,
    *,
    model: str = "test/model",
    endpoint: str = "http://127.0.0.1:1240/v1",
) -> dict:
    receipt = {
        "schema_version": "playground-isolated-vlm-runtime-receipt-v1",
        "generated_at": "2026-08-27T08:00:00+00:00",
        "status": "isolated_started_and_verified",
        "backend": {
            "kind": "llama.cpp-direct",
            "release": "0.2.0-dev",
            "build": 10566,
            "commit": "bb4caa754",
            "binary_sha256": "a" * 64,
            "binary_size_bytes": 123456,
        },
        "model": {
            "identifier": model,
            "gguf_sha256": "b" * 64,
            "gguf_size_bytes": 654321,
            "mmproj_sha256": "c" * 64,
            "mmproj_size_bytes": 111111,
        },
        "requested_settings": {
            "host": "127.0.0.1",
            "port": 1240,
            "endpoint": endpoint,
            "context_length": 8192,
            "gpu_offload": "max",
            "gpu_layers": "all",
            "parallel": 1,
            "device": "CUDA0",
            "split_mode": "none",
            "fit_enabled": True,
            "fit_target": 256,
            "fit_context": 8192,
            "batch_size": 2048,
            "micro_batch_size": 512,
            "threads": 4,
            "kv_key_type": "f16",
            "kv_value_type": "f16",
            "flash_attention": "auto",
            "kv_offload": True,
            "kv_unified": True,
            "device_io_disabled": True,
            "memory_lock": True,
            "metrics_enabled": True,
            "reasoning_format": "deepseek",
            "reasoning_budget": 256,
            "reasoning_budget_message": "I have to answer now.",
            "mmproj_enabled": True,
            "webui_enabled": False,
            "api_key_configured": False,
        },
        "isolation_verification": {
            "bionic_server_suspended": True,
            "bionic_loaded_model_count": 0,
            "bionic_cli_commit": "71bd99c",
            "bionic_cli_locator": "test_locator",
            "owned_pid": 4242,
            "port_owner_pid": 4242,
            "pid_port_owner_match": True,
            "process_image_sha256": "a" * 64,
            "process_image_hash_match": True,
            "health_status": "ok",
            "served_model_ids": [model],
            "status": "pass",
        },
        "attestation_boundary": "Paths and the process command line are intentionally omitted.",
        "safety": {
            "public_safe": True,
            "contains_credentials": False,
            "contains_process_command_line": False,
            "contains_executable_path": False,
            "contains_model_path": False,
            "contains_private_media_path": False,
        },
    }
    path.write_text(json.dumps(receipt), encoding="utf-8")
    return receipt
